# Generated by Django 5.0 on 2024-03-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вида тренировки')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название вида тренировки')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Название вида тренировки')),
            ],
            options={
                'verbose_name': ' Вид тренера',
                'verbose_name_plural': 'Виды  тренеров',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фамилия Имя')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Фамилия Имя')),
                ('name_ky', models.CharField(max_length=250, null=True, verbose_name='Фамилия Имя')),
                ('position', models.CharField(max_length=250, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=250, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=250, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(default='/trainer/default.jpg', upload_to='trainer/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('section', models.CharField(default='trainer', max_length=200)),
                ('type_of_trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.type_of_trainer', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
