# Generated by Django 5.0 on 2024-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.CharField(default='trainers', editable=False, max_length=50),
        ),
    ]
