# Generated by Django 5.0 on 2024-03-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='type',
        ),
    ]
