# Generated by Django 5.0 on 2024-03-28 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='desc_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='описание'),
        ),
    ]
