# Generated by Django 5.0.3 on 2024-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_desc_alter_vacancy_desc_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
    ]
