# Generated by Django 5.0 on 2024-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('jobtitle', models.CharField(max_length=255, verbose_name='Должность')),
                ('jobtitle_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('jobtitle_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Отзыв')),
                ('description_ru', models.TextField(null=True, verbose_name='Отзыв')),
                ('description_ky', models.TextField(null=True, verbose_name='Отзыв')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
