# Generated by Django 5.0 on 2024-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(upload_to='review/', verbose_name='Фотография'),
        ),
    ]
