# Generated by Django 5.0.3 on 2024-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_alter_review_description_alter_review_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
    ]
