# Generated by Django 5.0 on 2024-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(max_length=200, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(max_length=200, null=True, verbose_name='Подзаголовок')),
                ('photo', models.FileField(upload_to='homepage/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Стартовый блок',
                'verbose_name_plural': 'Стартовый блок',
            },
        ),
    ]
