# Generated by Django 5.0 on 2024-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('note_ru', models.CharField(max_length=255, null=True, verbose_name='Примечание')),
                ('note_ky', models.CharField(max_length=255, null=True, verbose_name='Примечание')),
                ('hours_week', models.CharField(max_length=255, verbose_name='Кол-во часов в неделю')),
                ('hours_week_ru', models.CharField(max_length=255, null=True, verbose_name='Кол-во часов в неделю')),
                ('hours_week_ky', models.CharField(max_length=255, null=True, verbose_name='Кол-во часов в неделю')),
                ('price', models.CharField(max_length=255, verbose_name='Стоимость')),
                ('price_ru', models.CharField(max_length=255, null=True, verbose_name='Стоимость')),
                ('price_ky', models.CharField(max_length=255, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
    ]
