# Generated by Django 5.0.3 on 2024-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='price_ky',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price_ru',
        ),
    ]
