# Generated by Django 5.0 on 2024-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('desc_ru', models.TextField(null=True, verbose_name='Описание')),
                ('desc_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': ('О нас',),
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
