# Generated by Django 5.0 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Срок абонемента')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Срок абонемента')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Срок абонемента')),
                ('mark_freeze', models.CharField(choices=[('✔', '✔'), ('🞬', '🞬')], default='✔', max_length=2, verbose_name='Есть ли заморозка?')),
                ('freeze', models.CharField(max_length=200, verbose_name='Кол-во дней заморозки')),
                ('freeze_ru', models.CharField(max_length=200, null=True, verbose_name='Кол-во дней заморозки')),
                ('freeze_ky', models.CharField(max_length=200, null=True, verbose_name='Кол-во дней заморозки')),
                ('mark_trainer', models.CharField(choices=[('✔', '✔'), ('🞬', '🞬')], default='✔', max_length=2, verbose_name='Есть ли спец тренеры?')),
                ('trainer', models.CharField(max_length=200, verbose_name='Кол-во спец тренеров')),
                ('trainer_ru', models.CharField(max_length=200, null=True, verbose_name='Кол-во спец тренеров')),
                ('trainer_ky', models.CharField(max_length=200, null=True, verbose_name='Кол-во спец тренеров')),
                ('mark_guest', models.CharField(choices=[('✔', '✔'), ('🞬', '🞬')], default='✔', max_length=2, verbose_name='Есть ли гостевые визитов?')),
                ('guest', models.CharField(max_length=200, verbose_name='Кол-во дней гостевых визитов')),
                ('guest_ru', models.CharField(max_length=200, null=True, verbose_name='Кол-во дней гостевых визитов')),
                ('guest_ky', models.CharField(max_length=200, null=True, verbose_name='Кол-во дней гостевых визитов')),
                ('time', models.CharField(max_length=150, verbose_name='Время посещения')),
                ('time_ru', models.CharField(max_length=150, null=True, verbose_name='Время посещения')),
                ('time_ky', models.CharField(max_length=150, null=True, verbose_name='Время посещения')),
                ('price', models.CharField(max_length=20, verbose_name='Стоимость')),
                ('price_ru', models.CharField(max_length=20, null=True, verbose_name='Стоимость')),
                ('price_ky', models.CharField(max_length=20, null=True, verbose_name='Стоимость')),
                ('special', models.BooleanField(verbose_name='Специальное предложение?')),
            ],
            options={
                'verbose_name': ('Абонемент',),
                'verbose_name_plural': 'Абонементы',
            },
        ),
    ]
