# Generated by Django 5.0 on 2024-03-29 14:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('section', models.CharField(default='trainer', max_length=200)),
            ],
            options={
                'verbose_name': ('Тренировочная зона',),
                'verbose_name_plural': 'Тренировочные зоны',
            },
        ),
        migrations.CreateModel(
            name='TrainZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='media/')),
                ('trainzone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TrainZone.trainzone')),
            ],
        ),
    ]
