# Generated by Django 5.0 on 2024-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='hide',
            field=models.BooleanField(default=1, verbose_name='Cкрыть'),
            preserve_default=False,
        ),
    ]
