# Generated by Django 5.0 on 2024-03-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offering', '0002_offering_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offering.icons', verbose_name='картинки услуг'),
        ),
    ]
