# Generated by Django 5.0.3 on 2024-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ky', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ на вопрос')),
                ('answer_ky', models.TextField(null=True, verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
