# Generated by Django 5.0 on 2024-03-28 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопрос'),
        ),
    ]
