# Generated by Django 5.0 on 2024-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название_файла')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Название_файла')),
                ('name_ky', models.CharField(max_length=40, null=True, verbose_name='Название_файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('file_ky', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
